changelog:
  categories:
    - title: Features
      labels:
        - ':mushroom: enhancement'
    - title: Bug Fixes
      labels:
        - ':beetle: bug'
    - title: Behind the Scenes
      labels:
        - ':gear: infrastructure'
        - ':robot:'
    - title: Documentation
      labels:
        - ':books: docs'
    # Not for published notes, just to make sure we don't forget any accidentally unlabeled PRs
    - title: Uncategorized
      labels:
        - '*'
